version: 2.1
orbs:
  newman: postman/newman@0.0.2
  discord: antonioned/discord@0.1.0
jobs:
  PS5-Stock:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run:
         command: apk update; apk add bash curl curl-dev
      - newman/newman-run:
          collection: ./Stock.postman_collection.json
      - discord/status:
          webhook: "${DISCORD_STATUS_WEBHOOK}"
          fail_only: false
          failure_message: "WH PS5 DISK https://bit.ly/3lMC2bt ...................................................................................
          WH PS5 DIGITAL https://bit.ly/3Avb1zj ................................................................................
          WH XBOX HALO https://bit.ly/2XFKOjG ..............................................................................
          NL PS5 DISK https://bit.ly/3EFhSZD ...................................................................................
          NL PS5 DIGITAL https://bit.ly/3u82AYA ..............................................................................
          NL XBoxX https://bit.ly/3EPMNma ......................................................................................
          JB XBoxX https://bit.ly/39oP7lB ..........................................................................................
          MA XBoxX https://bit.ly/3lFB54w ..........................................................................................
          MA PS5 DIGITAL https://bit.ly/2W4e6Ym ................................................................................"
          success_message: "WH PS5 DISK https://bit.ly/3lMC2bt ...................................................................................
          WH PS5 DIGITAL https://bit.ly/3Avb1zj ................................................................................
          WH XBOX HALO https://bit.ly/2XFKOjG ..............................................................................
          NL PS5 DISK https://bit.ly/3EFhSZD ...................................................................................
          NL PS5 DIGITAL https://bit.ly/3u82AYA ..............................................................................
          NL XBoxX https://bit.ly/3EPMNma ......................................................................................
          JB XBoxX https://bit.ly/39oP7lB ..........................................................................................
          MA XBoxX https://bit.ly/3lFB54w ..........................................................................................
          MA PS5 DIGITAL https://bit.ly/2W4e6Ym ................................................................................"
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - PS5-Stock
  daily:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 22,23,0,1,2,3,4,5 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - PS5-Stock
